version: "3.9"

services:
  backend:
    container_name: backend
    build: ./backend
    restart: always
    environment:
      - ALLOWED_HOSTS=backend
      - CISO_ASSISTANT_URL=https://localhost:8443
      - DJANGO_DEBUG=True
    volumes:
      - ./db:/code/db

  frontend:
    container_name: frontend
    environment:
        - ORIGIN=https://localhost:8443
        - PUBLIC_BACKEND_API_URL=http://backend:8000/api
    build: ./frontend
    depends_on:
      - backend

  caddy:
    container_name: caddy
    image: caddy:2.7.6
    restart: unless-stopped
    ports:
      - 8443:8443
    command:
        - caddy
        - reverse-proxy
        - --from
        - https://localhost:8443
        - --to
        - frontend:3000
    volumes:
      - ./db:/data
